### ISSUE TITLE
`DynamoDbLocal` dependency doesn't exist

### ISSUE THREAD

**Issue by codan84** [awslabs/aws-dynamodb-examples#1]
Cloned this repo, maven won't find `DynamoDbLocal` dependency. When following the link to "DynamoDb Local Release Repository" (http://dynamodb-local.s3-website-us-west-2.amazonaws.com/release) I will get `403 Forbidden`.

**Comment by amcp** [comment]
Hello, thanks for bringing this up. I just tried this: `rm -rf ~/.m2/repository/com/amazonaws/DynamoDBLocal/` and then `mvn install` and then `mvn test -Pstart-dynamodb-local` and I was able to bring up the shell at http://localhost:8000/shell/, please confirm that it works now.

**Comment by codan84** [comment]
After a lengthy process of trying to debug this, it turns out it was in fact my maven config messing things up. I can confirm that this works fine now.
