### ISSUE TITLE
mvn clean package failed

### ISSUE THREAD

**Issue by ikzjfr0** [awslabs/aws-dynamodb-examples#14]
when executing "mvn clean package", comes an error:

[ERROR] Failed to execute goal on project aws-dynamodb-examples: Could not resolve dependencies for project com.amazonaws:aws-dynamodb-examples:jar:1.0.0: Failed to collect dependencies at com.amazonaws:DynamoDBLocal:jar:[1.11.86,2.0): No versions available for com.amazonaws:DynamoDBLocal:jar:[1.11.86,2.0) within specified range -> [Help 1]

**Comment by amcp** [comment]
I just ran `mvn clean package` and it succeeded. Closing.
