### ISSUE TITLE
No versions available for com.amazonaws:DynamoDBLocal:jar:[1.11.86,2.0)

### ISSUE THREAD

**Issue by mmeier** [awslabs/aws-dynamodb-examples#15]
Cloned the repository and ran `mvn test` but the build failed with the following error:

`[ERROR] Failed to execute goal on project aws-dynamodb-examples: Could not resolve dependencies for project com.amazonaws:aws-dynamodb-examples:jar:1.0.0: Failed to collect dependencies at com.amazonaws:DynamoDBLocal:jar:[1.11.86,2.0): No versions available for com.amazonaws:DynamoDBLocal:jar:[1.11.86,2.0) within specified range -> [Help 1]`

**Comment by amcp** [comment]
When I checked this repository out today and ran both `mvn clean test` and `mvn test` I observed successful builds. Closing.

**Comment by it-worker23** [comment]
I am having the same issue

**Comment by tekumara** [comment]
I found the following worked:
```
    <repositories>
        <repository>
            <id>dynamodblocal</id>
            <name>AWS DynamoDB Local Release Repository</name>
            <url>https://s3-us-west-2.amazonaws.com/dynamodb-local/release</url>
        </repository>
    </repositories>
```

```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>DynamoDBLocal</artifactId>
            <version>[1.11.119,2.0)</version>
        </dependency>
```
