### ISSUE TITLE
Dynamodb-local dependency failure again.

### ISSUE THREAD

**Issue by allonbendavid** [awslabs/aws-dynamodb-examples#16]
This follows the same issue as the pre-February (2017) failures when the repo was changed to HTTPS.  Cannot build the examples currently:

**Could not resolve dependencies for project com.amazonaws:aws-dynamodb-examples:jar:1.0.0: Failed to collect dependencies at com.amazonaws:DynamoDBLocal:jar:[1.11.89,2.0.0)**

Have the current repo setting in my pom:

`<repository>
            <id>dynamodblocal</id>
            <name>AWS DynamoDB Local Release Repository</name>
            <url>https://s3-us-west-2.amazonaws.com/dynamodb-local/release</url>
        </repository>`

**Comment by franciscodominguez** [comment]
I experiencing the same thing

**Comment by jestrange** [comment]
I'm experiencing this as well.

**Comment by allonbendavid** [comment]
I ended up resolving this a while back so I don't really remember the specifics, but I think it was due to some aggressive Maven repository settings in your settings.xml (~/.m2/settings.xml).  Just temporarily remove the settings file (it's not required) and then try building again.  Once it's downloaded into your local then you can put your settings.xml file back.

**Comment by jestrange** [comment]
That resolved it for me as well; thanks for the update!

**Comment by temadison** [comment]
@allonbendavid You saved me a few gray hairs ... thank you.  Had to first remove the DynamoDBLocal folder from the repository and then, after temporarily removing the settings.xml file, did a "maven install -U" and voila, the full version of the jar file was downloaded.  Many thanks.

**Comment by allonbendavid** [comment]
Cool!
