### ISSUE TITLE
DynamoDB Local Repository broken [HTTP Response 404]

### ISSUE THREAD

**Issue by philgebhardt** [awslabs/aws-dynamodb-examples#7]
Trying to use the maven repository for dynamodb local artifacts. The hosted repository (http://dynamodb-local.s3-website-us-west-2.amazonaws.com/release) is returning HTTP 404 errors.

Getting build errors from gradle.

```
Could not resolve all dependencies for configuration ':testCompile'.
Could not find any matches for com.amazonaws:DynamoDBLocal:1.+ as no versions of com.amazonaws:DynamoDBLocal are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/amazonaws/DynamoDBLocal/maven-metadata.xml
         https://jcenter.bintray.com/com/amazonaws/DynamoDBLocal/
         https://repo1.maven.org/maven2/com/amazonaws/DynamoDBLocal/maven-metadata.xml
         https://repo1.maven.org/maven2/com/amazonaws/DynamoDBLocal/
         http://dynamodb-local.s3-website-us-west-2.amazonaws.com/release/com/amazonaws/DynamoDBLocal/maven-metadata.xml
         http://dynamodb-local.s3-website-us-west-2.amazonaws.com/release/com/amazonaws/DynamoDBLocal/
```

**Comment by philgebhardt** [comment]
Changing the repository URL to `https://s3-us-west-2.amazonaws.com/dynamodb-local/release` fixes the dependency resolution problem.

From: `http://dynamodb-local.s3-website-us-west-2.amazonaws.com/release`
To: `https://s3-us-west-2.amazonaws.com/dynamodb-local/release`

Inspecting the two urls, this looks like the same s3 bucket. Could this perhaps be an issue with the S3 service itself?

**Comment by buremba** [comment]
It broke our production deployment.

**Comment by dymaws** [comment]
Apologies for the inconvenience, as a security measure we stopped serving traffic via HTTP, but failed to update all relevant documentation. For the time being, we have re-enabled HTTP traffic, but will be migrating to HTTPs only in the near future. 

Please use this HTTPs link in your pom file:
https://s3-us-west-2.amazonaws.com/dynamodb-local/release

We will be updating the official AWS docs soon to notify everyone of this change.

**Comment by buremba** [comment]
please please please inform us before making this kind of change. it may seem like a simple change change but maven cannot know the new urls so you can break our continuous integration and deployment systems with this small change. you may at least redirect traffic to https and update the docs before making any backward incompatible change.

**Comment by ikzjfr0** [comment]
when accessing: https://s3-us-west-2.amazonaws.com/dynamodb-local/release
it comes an error:

<ErrorError>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>release</Key>
<RequestId>10C05F0C9DDA579A</RequestId>
<HostId>FgsMC8+3I4sC+b/CP/G5dw9aFRriHfccEfiyki0xsr661jW6Vfr+jXIojgO2feNd4jc49t6omYA=</HostId>
</Error>

**Comment by tekumara** [comment]
I found the following worked:
```
    <repositories>
        <repository>
            <id>dynamodblocal</id>
            <name>AWS DynamoDB Local Release Repository</name>
            <url>https://s3-us-west-2.amazonaws.com/dynamodb-local/release</url>
        </repository>
    </repositories>
```

```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>DynamoDBLocal</artifactId>
            <version>[1.11.119,2.0)</version>
        </dependency>
```

**Comment by tekumara** [comment]
If you want the latest version it can be found here https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
